### ISSUE TITLE
slow!  try this:

### ISSUE THREAD

**Issue by Zibri** [kunstmusik/audioworklet-serviceworker#1]
process(inputs, outputs, parameters) {
            const output = outputs[0];
            const amplitude = parameters.amplitude[0];

            const outputChannel = output[0];

            outputChannel.set(outputChannel.map( (c,i)=>amplitude * ( 2 * (Math.random() - 0.5) )  ) );

            return true;
        }

**Comment by kunstmusik** [comment]
Closing as this was a test project and will not be updated. Also, I'm pretty sure outputChannel.map() will end up creating new array objects every process call which would end up accelerating the rate of GC calls.
